In [57]:
import xarray as xr
import pandas as pd
from joblib import load
import os
import math
from datetime import datetime,timedelta
from sklearn import preprocessing

In [2]:
def redondeo(coordenadas, base=1/12):
    """
    Devuelve las coordenadas pasadas redondeadas
    
    Parametros:
    coordenadas -- lista de latitud y longitud
    base -- base del redondeo
    """
    return  base * round(coordenadas/base)

In [3]:
fecha = '2018-11-16'
coordenadas = '[-26.99053888888889, -70.78993333333334]'
salto = 1/12
var = ['mlotst','zos','bottomT','thetao','so','uo','vo']

In [4]:
separacion = coordenadas.index(', ')
final = coordenadas.index(']')
coordenadas = [float(coordenadas[1:separacion]),float(coordenadas[separacion+2:final])]
coordenadas = [redondeo(coordenadas[0]),redondeo(coordenadas[1])]
coordenadas

[-27.0, -70.75]

In [63]:
def genera_resultados(fecha, coordenadas):
    # se cogerian los datos de copernicus
    # generar dataframe
    #normalizarlo
    # meterlo al modelo
    modelo = load('C:\\Users\pablo\Desktop\medusas\static\modelo.joblib')
    df,fechas = genera_estructura(fecha,coordenadas)
    df = normaliza_min_max(df)
    salida = modelo.predict(df)
    print(salida,fechas)
    
#     lista = [{'y': '2020-1-1', 'v': 1},
#              {'y': '2020-2-1', 'v': 10},
#              {'y': '2020-1-5', 'v': 5},
#              {'y': '2020-3-5', 'v': 2}]
#     return lista
    return df

In [53]:
def genera_estructura(f,c):
    dataframe = pd.DataFrame(columns=list(range(231)))
    fechas = genera_fechas(f)
    for index,dia in enumerate(fechas):
        listado_variables = []
        # cargo el dataset
        ds =busca_archivo(dia) # cambiar para cada dia
        c = comprueba_datos(c[0],c[1],ds)
        coord = dame_coordenadas(c)

        for j in coord:
            variables1 = ds.sel({'latitude':coord[0][0],'longitude': coord[0][1], 'depth' : 0 },method='nearest').to_dataframe()
            l1 = dame_lista(variables1)[0]
            variables2 = ds.sel({'latitude':coord[1][0],'longitude': coord[1][1], 'depth' : 5 },method='nearest').to_dataframe()
            l2 = dame_lista(variables2)[0]
            variables3 = ds.sel({'latitude':coord[2][0],'longitude': coord[2][1], 'depth' : 10},method='nearest').to_dataframe()
            l3 = dame_lista(variables3)[0]
            l1+=l2
            l1+=l3
            listado_variables+=(l1)
        dataframe.loc[index] = listado_variables
    return dataframe,fechas

In [67]:
def normaliza_min_max(df_atributos):
    """
    Normaliza los datos del dataframe pasado
    """
    X = df_atributos.values.tolist()
    n = load('normalizador.pkl') 
    x_normalizado_2 = n.transform(X)
    df_norm = pd.DataFrame(x_normalizado_2,columns=list(range(231)))
    return df_norm

In [55]:
def genera_fechas(f):
    lista_fechas = []
    for i in range(5):
        fecha= datetime.strptime(f, '%Y-%m-%d')
        fecha += timedelta(days=i)
        lista_fechas.append(str(fecha))
    return lista_fechas

def dame_lista(df):
    Row_list = []
    for index, rows in df.iterrows(): 
        my_list =[rows.mlotst, rows.zos, rows.bottomT, rows.thetao, rows.so,
                 rows.uo, rows.vo] 
        Row_list.append(my_list) 

    # Print the list 
    return Row_list

def busca_archivo(fecha):
    """
    Devuelve el archivo .nc de la fecha pasada por parametro
    
    Parametros:
    fecha -- fecha en formato AÃ±oMesDia (20140105)
    """
    listado_archivos = os.listdir('C:\\Users\pablo\Desktop\medusas\documentos\copernicus') # Listo todos los archivos de Copernicus
    texto ='_{}_'.format(str(fecha).split()[0].replace('-',''))
    archivo = [x for x in listado_archivos if str(texto) in x]
    data = xr.open_dataset('C:\\Users\pablo\Desktop\medusas\documentos\copernicus\{}'.format(archivo[0])) # cargo el archivo
    return data # devuelvo dataset

def dame_coordenadas(c):
    paso = 1/12
    return [[c[0],c[1]],
            [c[0],c[1]-paso],[c[0]+paso,c[1]-paso],[c[0]+(paso*2),c[1]-paso],[c[0]-paso,c[1]-paso],[c[0]-(paso*2),c[1]-paso],
           [c[0],c[1]-(2*paso)],[c[0]+paso,c[1]-(2*paso)],[c[0]+(paso*2),c[1]-(2*paso)],[c[0]-paso,c[1]-(2*paso)],[c[0]-(paso*2),c[1]-(2*paso)]]

def comprueba_datos(latitud,longitud,ds):
    """
    Comprueba si el dataset contiene valores en las coordenadas pasadas
    
    Devuelve las coordenadas mas cercanas con datos 
    
    Parametros:
    latitud -- latitud
    longitud -- longitud
    ds -- dataset del que extraer los valores
    """
    valor = dame_datos(latitud,longitud,ds)
    while math.isnan(valor.mlotst[0]):
        longitud = longitud - salto
        valor = dame_datos(latitud,longitud,ds)
    return latitud,longitud # devuelvo las coordenadas con datos

def dame_datos(latitud,longitud,ds):
    """
    Devuelve los datos del dataset en las coordenadas pasadas
    
    Parametros:
    latitud -- latitud 
    longitud -- longitud
    ds -- dataset del que extraer los valores
    """
    return ds.sel({'latitude':latitud,'longitude': longitud})

In [68]:
d = genera_resultados(fecha,coordenadas)
d

[100.   5.  23.  23.  17.]

,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
0,0.028272,0.415493,0.648856,0.376599,0.750570,0.273821,0.433501,0.023834,0.399173,0.730221,...,0.674680,0.327645,0.539053,0.004119,0.380342,0.718814,0.328468,0.664615,0.408931,0.387646
1,0.028272,0.424044,0.649685,0.337385,0.759949,0.283071,0.461538,0.024870,0.408997,0.737294,...,0.683333,0.350398,0.539053,0.011329,0.395833,0.715504,0.367581,0.671111,0.444183,0.414803
2,0.028272,0.425553,0.648186,0.333930,0.761977,0.363552,0.549964,0.039378,0.416753,0.731343,...,0.687500,0.453925,0.583432,0.036045,0.407051,0.706325,0.374262,0.674188,0.485311,0.473376
3,0.028272,0.438632,0.645939,0.377175,0.754626,0.475486,0.561467,0.030052,0.434850,0.724417,...,0.685256,0.590444,0.601183,0.028836,0.424679,0.702714,0.387948,0.675555,0.579318,0.496273
4,0.028272,0.431590,0.644401,0.398605,0.750317,0.481961,0.629044,0.023834,0.432265,0.718759,...,0.683013,0.593857,0.667456,0.012358,0.420940,0.703767,0.408575,0.673162,0.561692,0.546858